# app/social/config/__init__.py

"""Configuration module for PHASE 3"""

from .constants import (
    ENTITY_TYPES,
    RELATION_TYPES,
    SACRED_ENTITY_TYPES,
    EDGE_WEIGHT_ALPHA,
    EDGE_WEIGHT_BETA,
    TEMPORAL_PERIODS,
    SENTIMENT_ASPECTS,
    TRIP_TYPES,
    TOP_N_NODES,
    HUB_CENTRALITY_THRESHOLD,
    MIN_COMPONENT_SIZE,
    TRADITIONAL_NLP_ENTROPY_BASELINE,
    EXPORT_FORMATS,
    OUTPUT_DIR,
    PHASE_3_VERSION,
)

__all__ = [
    "ENTITY_TYPES",
    "RELATION_TYPES",
    "SACRED_ENTITY_TYPES",
    "EDGE_WEIGHT_ALPHA",
    "EDGE_WEIGHT_BETA",
    "TEMPORAL_PERIODS",
    "SENTIMENT_ASPECTS",
    "TRIP_TYPES",
    "TOP_N_NODES",
    "HUB_CENTRALITY_THRESHOLD",
    "MIN_COMPONENT_SIZE",
    "TRADITIONAL_NLP_ENTROPY_BASELINE",
    "EXPORT_FORMATS",
    "OUTPUT_DIR",
    "PHASE_3_VERSION",
]
